SQLMinID                33
SQLDefaultUID           110     #If UID < 33 set UID by Anonymous
SQLDefaultGID           65534   #Also for GID
SQLAuthTypes            Crypt
SQLAuthenticate         users
SQLConnectInfo          proftpd@localhost proftpd PaSSworD332
SQLUserInfo             users username password uid gid homedir shell
RequireValidShell       Off
SQLLogFile             /var/log/proftpd/sql.log        #UnComment ONLY FOR DEBUG MOD

